# Generated by Django 6.0.6 on 2026-06-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('judging', 'Judging'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
